# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import banking_pb2 as banking__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in banking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BankingServiceStub(object):
    """Banking RPC service matching the aiozmq interface
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendCommand = channel.unary_unary(
                '/banking.BankingService/SendCommand',
                request_serializer=banking__pb2.CommandRequest.SerializeToString,
                response_deserializer=banking__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.RaftMessage = channel.unary_unary(
                '/banking.BankingService/RaftMessage',
                request_serializer=banking__pb2.RaftRequest.SerializeToString,
                response_deserializer=banking__pb2.RaftResponse.FromString,
                _registered_method=True)


class BankingServiceServicer(object):
    """Banking RPC service matching the aiozmq interface
    """

    def SendCommand(self, request, context):
        """Send a banking command (JSON string) and receive response (JSON string)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RaftMessage(self, request, context):
        """Send a raft message and receive response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BankingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCommand,
                    request_deserializer=banking__pb2.CommandRequest.FromString,
                    response_serializer=banking__pb2.CommandResponse.SerializeToString,
            ),
            'RaftMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.RaftMessage,
                    request_deserializer=banking__pb2.RaftRequest.FromString,
                    response_serializer=banking__pb2.RaftResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'banking.BankingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('banking.BankingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BankingService(object):
    """Banking RPC service matching the aiozmq interface
    """

    @staticmethod
    def SendCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banking.BankingService/SendCommand',
            banking__pb2.CommandRequest.SerializeToString,
            banking__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RaftMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banking.BankingService/RaftMessage',
            banking__pb2.RaftRequest.SerializeToString,
            banking__pb2.RaftResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
