# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: banking.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'banking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbanking.proto\x12\x07\x62\x61nking\"!\n\x0e\x43ommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"!\n\x0f\x43ommandResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x1e\n\x0bRaftRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0cRaftResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\x8e\x01\n\x0e\x42\x61nkingService\x12@\n\x0bSendCommand\x12\x17.banking.CommandRequest\x1a\x18.banking.CommandResponse\x12:\n\x0bRaftMessage\x12\x14.banking.RaftRequest\x1a\x15.banking.RaftResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'banking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDREQUEST']._serialized_start=26
  _globals['_COMMANDREQUEST']._serialized_end=59
  _globals['_COMMANDRESPONSE']._serialized_start=61
  _globals['_COMMANDRESPONSE']._serialized_end=94
  _globals['_RAFTREQUEST']._serialized_start=96
  _globals['_RAFTREQUEST']._serialized_end=126
  _globals['_RAFTRESPONSE']._serialized_start=128
  _globals['_RAFTRESPONSE']._serialized_end=158
  _globals['_BANKINGSERVICE']._serialized_start=161
  _globals['_BANKINGSERVICE']._serialized_end=303
# @@protoc_insertion_point(module_scope)
