* Test from file tests/test_partition_1.py


    This is a basic test of network partitioning and recovery. Five nodes are
    started and brought into sync after and election. Then two nodes are
    configured to be on a different simulated network partition than the
    leader and two other nodes. This means that the leader still has a quorum
    and can continue to advance the log. So, the leader runs a couple of commands
    after partition and we check to see that the reachable nodes get updated
    properly. We also check that the unreachable ones don't, but that is more
    about testing the simulation rather than any raft feature.

    One these verifications are done, the isolated nodes are configured to rejoin
    the main network and the leader is prodded to do a heartbeat broadcast. Some
    fiddly simulation control bits are used to single step through the message
    delivery process so as to verify that each heartbeat message reaches
    the right target and the target does the correct state ops and encodes
    the right reply. The rejoined nodes should walk through the state changes
    until they have correctly replicated the leader's log and the simulation
    state machine's final state.

    Timers are disabled, so all timer driven operations such as heartbeats are manually triggered.
    


 *[[condensed Trace Table Legend][Table legend]] located after last table in file*

** Initial election, normal
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| event | N-1   | N-1                              | N-1       | N-2   | N-2      | N-2       | N-3   | N-3      | N-3       | N-4   | N-4      | N-4       | N-5   | N-5      | N-5       |
| node  | Role  | Op                               | Delta     | Role  | Op       | Delta     | Role  | Op       | Delta     | Role  | Op       | Delta     | Role  | Op       | Delta     |
|  N-1  | FLWR  | STARTED                          |           | FLWR  | STARTED  |           | FLWR  | STARTED  |           | FLWR  | STARTED  |           | FLWR  | STARTED  |           |
|  N-1  | CNDI  | NEW ROLE                         | t=1       | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           |
|  N-1  | CNDI  | give_vote->N-2 term=1 li=0 lt=1  |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           |
|  N-1  | CNDI  | give_vote->N-3 term=1 li=0 lt=1  |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           |
|  N-1  | CNDI  | give_vote->N-4 term=1 li=0 lt=1  |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           |
|  N-1  | CNDI  | give_vote->N-5 term=1 li=0 lt=1  |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           |
|  N-1  | CNDI  | N-2->vote  yes=True              |           | FLWR  |          | t=1       | FLWR  |          | t=1       | FLWR  |          | t=1       | FLWR  |          | t=1       |
|  N-1  | CNDI  | N-3->vote  yes=True              |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           |
|  N-1  | LEAD  | NEW ROLE                         | lt=1 li=1 | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           |
|  N-1  | LEAD  | entries->N-2 li=0 lt=0 ec=1 ci=0 |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           |
|  N-1  | LEAD  | entries->N-3 li=0 lt=0 ec=1 ci=0 |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           |
|  N-1  | LEAD  | entries->N-4 li=0 lt=0 ec=1 ci=0 |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           |
|  N-1  | LEAD  | entries->N-5 li=0 lt=0 ec=1 ci=0 |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           |
|  N-1  | LEAD  | N-4->vote  yes=True              |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           |
|  N-1  | LEAD  | N-5->vote  yes=True              |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           |
|  N-1  | LEAD  | N-2->ent_reply  ok=True mi=1     |           | FLWR  |          | lt=1 li=1 | FLWR  |          | lt=1 li=1 | FLWR  |          | lt=1 li=1 | FLWR  |          | lt=1 li=1 |
|  N-1  | LEAD  | N-3->ent_reply  ok=True mi=1     |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           |
|  N-1  | LEAD  | N-4->ent_reply  ok=True mi=1     | ci=1      | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           |
|  N-1  | LEAD  | N-5->ent_reply  ok=True mi=1     |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           | FLWR  |          |           |
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
** Run one command, normal sequence till leader commit, check follower's final state
----------------------------------------------------------------------------------------------------------------------------------------------------
| event | N-1   | N-1                              | N-1   | N-2   | N-2 | N-2   | N-3   | N-3 | N-3   | N-4   | N-4 | N-4   | N-5   | N-5 | N-5   |
| node  | Role  | Op                               | Delta | Role  | Op  | Delta | Role  | Op  | Delta | Role  | Op  | Delta | Role  | Op  | Delta |
|  N-1  | LEAD  | CMD START                        |       | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | entries->N-2 li=1 lt=1 ec=1 ci=1 | lt=1  | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | entries->N-3 li=1 lt=1 ec=1 ci=1 |       | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | entries->N-4 li=1 lt=1 ec=1 ci=1 |       | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | entries->N-5 li=1 lt=1 ec=1 ci=1 |       | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | N-2->ent_reply  ok=True mi=2     |       | FLWR  |     | lt=1  | FLWR  |     | lt=1  | FLWR  |     | lt=1  | FLWR  |     | lt=1  |
|  N-1  | LEAD  | N-3->ent_reply  ok=True mi=2     |       | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | N-4->ent_reply  ok=True mi=2     |       | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | N-5->ent_reply  ok=True mi=2     |       | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | CMD DONE                         | ci=2  | FLWR  |     | ci=2  | FLWR  |     | ci=2  | FLWR  |     | ci=2  | FLWR  |     | ci=2  |
|  N-1  | LEAD  | N-2->ent_reply  ok=True mi=2     |       | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | N-3->ent_reply  ok=True mi=2     |       | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | N-4->ent_reply  ok=True mi=2     |       | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | N-5->ent_reply  ok=True mi=2     |       | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       |
----------------------------------------------------------------------------------------------------------------------------------------------------
** Partitioning the network to isolate nodes 2 and 3
-----------------------------------------------------------------------------------------------------------------------------------
| event | N-1   | N-1 | N-1   | N-2   | N-2       | N-2   | N-3   | N-3       | N-3   | N-4   | N-4 | N-4   | N-5   | N-5 | N-5   |
| node  | Role  | Op  | Delta | Role  | Op        | Delta | Role  | Op        | Delta | Role  | Op  | Delta | Role  | Op  | Delta |
|  N-2  | LEAD  |     |       | FLWR  | NETSPLIT  |       | FLWR  |           |       | FLWR  |     |       | FLWR  |     |       |
|  N-3  | LEAD  |     |       | FLWR  |           | n=2   | FLWR  | NETSPLIT  | n=2   | FLWR  |     |       | FLWR  |     |       |
-----------------------------------------------------------------------------------------------------------------------------------
** Running two commands, only nodes 1, 4 and 5 should participate
----------------------------------------------------------------------------------------------------------------------------------------------------
| event | N-1   | N-1                              | N-1   | N-2   | N-2 | N-2   | N-3   | N-3 | N-3   | N-4   | N-4 | N-4   | N-5   | N-5 | N-5   |
| node  | Role  | Op                               | Delta | Role  | Op  | Delta | Role  | Op  | Delta | Role  | Op  | Delta | Role  | Op  | Delta |
|  N-1  | LEAD  | CMD START                        |       | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | entries->N-4 li=2 lt=1 ec=1 ci=2 | lt=1  | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | entries->N-5 li=2 lt=1 ec=1 ci=2 |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | N-4->ent_reply  ok=True mi=3     |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |     | lt=1  | FLWR  |     | lt=1  |
|  N-1  | LEAD  | N-5->ent_reply  ok=True mi=3     |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | CMD DONE                         | ci=3  | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |     | ci=3  | FLWR  |     | ci=3  |
|  N-1  | LEAD  | N-4->ent_reply  ok=True mi=3     |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | N-5->ent_reply  ok=True mi=3     |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | CMD START                        |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | entries->N-4 li=3 lt=1 ec=1 ci=3 | lt=1  | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | entries->N-5 li=3 lt=1 ec=1 ci=3 |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | N-4->ent_reply  ok=True mi=4     |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |     | lt=1  | FLWR  |     | lt=1  |
|  N-1  | LEAD  | N-5->ent_reply  ok=True mi=4     |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | CMD DONE                         | ci=4  | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |     | ci=4  | FLWR  |     | ci=4  |
|  N-1  | LEAD  | N-4->ent_reply  ok=True mi=4     |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | N-5->ent_reply  ok=True mi=4     |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |     |       | FLWR  |     |       |
----------------------------------------------------------------------------------------------------------------------------------------------------
** Healing network, nodes 2 and 3 will now be reachable from leader node 1, sending heartbeats
--------------------------------------------------------------------------------------------------------------------------------------------------------------
| event | N-1   | N-1                              | N-1   | N-2   | N-2      | N-2   | N-3   | N-3      | N-3   | N-4   | N-4 | N-4   | N-5   | N-5 | N-5   |
| node  | Role  | Op                               | Delta | Role  | Op       | Delta | Role  | Op       | Delta | Role  | Op  | Delta | Role  | Op  | Delta |
|  N-2  | LEAD  |                                  |       | FLWR  | NETJOIN  | n=1   | FLWR  |          |       | FLWR  |     |       | FLWR  |     |       |
|  N-3  | LEAD  |                                  |       | FLWR  |          |       | FLWR  | NETJOIN  | n=1   | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | entries->N-2 li=4 lt=1 ec=0 ci=4 |       | FLWR  |          |       | FLWR  |          |       | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | entries->N-3 li=4 lt=1 ec=0 ci=4 |       | FLWR  |          |       | FLWR  |          |       | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | entries->N-4 li=4 lt=1 ec=0 ci=4 |       | FLWR  |          |       | FLWR  |          |       | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | entries->N-5 li=4 lt=1 ec=0 ci=4 |       | FLWR  |          |       | FLWR  |          |       | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | N-4->ent_reply  ok=True mi=4     |       | FLWR  |          |       | FLWR  |          |       | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | N-5->ent_reply  ok=True mi=4     |       | FLWR  |          |       | FLWR  |          |       | FLWR  |     |       | FLWR  |     |       |
--------------------------------------------------------------------------------------------------------------------------------------------------------------
** Nodes 4 and 5 have processed heartbeats, now nodes 2 and 3 should do so
------------------------------------------------------------------------------------------------------------------------------------------------------------
| event | N-1   | N-1                              | N-1   | N-2   | N-2 | N-2       | N-3   | N-3 | N-3       | N-4   | N-4 | N-4   | N-5   | N-5 | N-5   |
| node  | Role  | Op                               | Delta | Role  | Op  | Delta     | Role  | Op  | Delta     | Role  | Op  | Delta | Role  | Op  | Delta |
|  N-1  | LEAD  | N-2->ent_reply  ok=False mi=2    |       | FLWR  |     |           | FLWR  |     |           | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | entries->N-2 li=2 lt=1 ec=1 ci=4 |       | FLWR  |     |           | FLWR  |     |           | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | N-2->ent_reply  ok=True mi=3     |       | FLWR  |     | lt=1 ci=3 | FLWR  |     |           | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | entries->N-2 li=3 lt=1 ec=1 ci=4 |       | FLWR  |     |           | FLWR  |     |           | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | N-2->ent_reply  ok=True mi=4     |       | FLWR  |     | lt=1 ci=4 | FLWR  |     |           | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | N-3->ent_reply  ok=False mi=2    |       | FLWR  |     |           | FLWR  |     |           | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | entries->N-3 li=2 lt=1 ec=1 ci=4 |       | FLWR  |     |           | FLWR  |     |           | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | N-3->ent_reply  ok=True mi=3     |       | FLWR  |     |           | FLWR  |     | lt=1 ci=3 | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | entries->N-3 li=3 lt=1 ec=1 ci=4 |       | FLWR  |     |           | FLWR  |     |           | FLWR  |     |       | FLWR  |     |       |
|  N-1  | LEAD  | N-3->ent_reply  ok=True mi=4     |       | FLWR  |     |           | FLWR  |     | lt=1 ci=4 | FLWR  |     |       | FLWR  |     |       |
------------------------------------------------------------------------------------------------------------------------------------------------------------



* Condensed Trace Table Legend
All the items in this table labeled N-X are placeholders for actual node id values,
actual values will be N-1, N-2, N-3, etc. up to the number of nodes in the cluster. Yes, One based, not zero.

| Column Label | Description     | Details                                                                                        |
| Event Node   | Triggering node | The id value of the node that experienced the event that triggered this trace row              |
| N-X Role     | Raft Role       | FLWR = Follower CNDI = Candidate LEAD = Leader                                                 |
| N-X Op       | Activity        | Describes a traceable event at this node, see separate table below                             |
| N-X Delta    | State change    | Describes any change in state since previous trace, see separate table below                   |


** "Op" Column detail legend
| Value          | Meaning                                                                                      |
| STARTED        | Simulated node starting with empty log, term=0                                               |
| CMD START      | Simulated client requested that a node (usually leader, but not for all tests) run a command |
| CMD DONE       | The previous requested command is finished, whether complete, rejected, failed, whatever     |
| CRASH          | Simulating node has simulated a crash                                                        |
| RESTART        | Previously crashed node has restarted. Look at delta column to see effects on log, if any    |
| NEW ROLE       | The node has changed Raft role since last trace line                                         |
| NETSPLIT       | The node has been partitioned away from the majority network                                 |
| NETJOIN        | The node has rejoined the majority network                                                   |
| endtries->N-X  | Node has sent append_entries message to N-X, next line in this table explains details        |
| (continued)    | li=1 means prevLogIndex=1, lt=1 means prevLogTerm=1, ci means sender's commitInde            |
| (continued)    | ec=2 means that the entries list in the is 2 items long. ec=0 is a heartbeat                 |
| N-X->ent_reply | Node has received the response to an append_entries message, details in continued lines      |
| (continued)    | ok=(True or False) means that entries were saved or not, mi=3 says log max index = 3         |
| give_vote->N-X | Node has sent request_vote to N-X, term=1 means current term is 1 (continued next line)      |
| (continued)    | li=0 means prevLogIndex = 0, lt=0 means prevLogTerm = 0                                      |
| N-X->vote      | Node has received request_vote response from N-X, yes=(True or False) indicates vote value   |


** "Delta" Column detail legend
Any item in this column indicates that the value of that item has changed since the last trace line

| Item | Meaning                                                                                                                         |
| t=X  | Term has changed to X                                                                                                           |
| lt=X | prevLogTerm has changed to X, indicating a log record has been stored                                                           |
| li=X | prevLogIndex has changed to X, indicating a log record has been stored                                                          |
| ci=X | Indicates commitIndex has changed to X, meaning log record has been committed, and possibly applied depending on type of record |
| n=X  | Indicates a change in networks status, X=1 means re-joined majority network, X=2 means partitioned to minority network          |




