* Test test_snapshot_3 from file tests/test_snapshots.py


    Test the simplest snapshot process, at a follower in a quiet cluster. After
    it is installed, have that node become the leader and make sure new commands
    work.

    Timers are disabled, so all timer driven operations such as heartbeats are manually triggered.
    
    


 *[[condensed Trace Table Legend][Table legend]] located after last table in file*

** Starting election at node 1 of 3
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|  N-1   | N-1                          | N-1       | N-2   | N-2                          | N-2       | N-3   | N-3                          | N-3       | N-4  | N-4 | N-4   |
|  Role  | Op                           | Delta     | Role  | Op                           | Delta     | Role  | Op                           | Delta     | Role | Op  | Delta |
|  FLWR  | STARTED                      |           | FLWR  | STARTED                      |           | FLWR  | STARTED                      |           |
|  CNDI  | NEW ROLE                     | t=1       | FLWR  |                              |           | FLWR  |                              |           |
|  CNDI  | poll->N-2 t=1 li=0 lt=1      |           | FLWR  |                              |           | FLWR  |                              |           |
|  CNDI  | poll->N-3 t=1 li=0 lt=1      |           | FLWR  |                              |           | FLWR  |                              |           |
|  CNDI  |                              |           | FLWR  | N-1->poll t=1 li=0 lt=1      | t=1       | FLWR  |                              |           |
|  CNDI  |                              |           | FLWR  | vote->N-1 yes=True           |           | FLWR  |                              |           |
|  CNDI  |                              |           | FLWR  |                              |           | FLWR  | N-1->poll t=1 li=0 lt=1      | t=1       |
|  CNDI  |                              |           | FLWR  |                              |           | FLWR  | vote->N-1 yes=True           |           |
|  LEAD  | N-2->vote yes=True           | lt=1 li=1 | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | NEW ROLE                     |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | ae->N-2 t=1 i=0 lt=0 e=1 c=0 |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | ae->N-3 t=1 i=0 lt=0 e=1 c=0 |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | N-3->vote yes=True           |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  |                              |           | FLWR  | N-1->ae t=1 i=0 lt=0 e=1 c=0 | lt=1 li=1 | FLWR  |                              |           |
|  LEAD  |                              |           | FLWR  | ae_reply->N-1 ok=True mi=1   |           | FLWR  |                              |           |
|  LEAD  |                              |           | FLWR  |                              |           | FLWR  | N-1->ae t=1 i=0 lt=0 e=1 c=0 | lt=1 li=1 |
|  LEAD  |                              |           | FLWR  |                              |           | FLWR  | ae_reply->N-1 ok=True mi=1   |           |
|  LEAD  | N-2->ae_reply ok=True mi=1   | ci=1      | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | N-3->ae_reply ok=True mi=1   |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | ae->N-2 t=1 i=1 lt=1 e=0 c=1 |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  |                              |           | FLWR  | N-1->ae t=1 i=1 lt=1 e=0 c=1 | ci=1      | FLWR  |                              |           |
|  LEAD  |                              |           | FLWR  | ae_reply->N-1 ok=True mi=1   |           | FLWR  |                              |           |
|  LEAD  | N-2->ae_reply ok=True mi=1   |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | ae->N-3 t=1 i=1 lt=1 e=0 c=1 |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  |                              |           | FLWR  |                              |           | FLWR  | N-1->ae t=1 i=1 lt=1 e=0 c=1 | ci=1      |
|  LEAD  |                              |           | FLWR  |                              |           | FLWR  | ae_reply->N-1 ok=True mi=1   |           |
|  LEAD  | N-3->ae_reply ok=True mi=1   |           | FLWR  |                              |           | FLWR  |                              |           |
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
** Telling leader node (node 1) to snapshot, should make it transfer power
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|  N-1   | N-1                                  | N-1         | N-2   | N-2                                  | N-2         | N-3   | N-3                              | N-3         | N-4  | N-4 | N-4   |
|  Role  | Op                                   | Delta       | Role  | Op                                   | Delta       | Role  | Op                               | Delta       | Role | Op  | Delta |
|  LEAD  | ae->N-2 t=1 i=101 lt=1 e=0 c=101     |             | FLWR  |                                      |             | FLWR  |                                  |             |
|  LEAD  |                                      |             | FLWR  | N-1->ae t=1 i=101 lt=1 e=0 c=101     |             | FLWR  |                                  |             |
|  LEAD  |                                      |             | FLWR  | ae_reply->N-1 ok=True mi=101         |             | FLWR  |                                  |             |
|  LEAD  | N-2->ae_reply ok=True mi=101         |             | FLWR  |                                      |             | FLWR  |                                  |             |
|  LEAD  | ae->N-3 t=1 i=101 lt=1 e=0 c=101     |             | FLWR  |                                      |             | FLWR  |                                  |             |
|  LEAD  |                                      |             | FLWR  |                                      |             | FLWR  | N-1->ae t=1 i=101 lt=1 e=0 c=101 |             |
|  LEAD  |                                      |             | FLWR  |                                      |             | FLWR  | ae_reply->N-1 ok=True mi=101     |             |
|  LEAD  | N-3->ae_reply ok=True mi=101         |             | FLWR  |                                      |             | FLWR  |                                  |             |
|  LEAD  | ae->N-2 t=1 i=101 lt=1 e=0 c=101     |             | FLWR  |                                      |             | FLWR  |                                  |             |
|  LEAD  |                                      |             | FLWR  | N-1->ae t=1 i=101 lt=1 e=0 c=101     |             | FLWR  |                                  |             |
|  LEAD  |                                      |             | FLWR  | ae_reply->N-1 ok=True mi=101         |             | FLWR  |                                  |             |
|  LEAD  | N-2->ae_reply ok=True mi=101         |             | FLWR  |                                      |             | FLWR  |                                  |             |
|  LEAD  | ae->N-3 t=1 i=101 lt=1 e=0 c=101     |             | FLWR  |                                      |             | FLWR  |                                  |             |
|  LEAD  |                                      |             | FLWR  |                                      |             | FLWR  | N-1->ae t=1 i=101 lt=1 e=0 c=101 |             |
|  LEAD  |                                      |             | FLWR  |                                      |             | FLWR  | ae_reply->N-1 ok=True mi=101     |             |
|  LEAD  | N-3->ae_reply ok=True mi=101         |             | FLWR  |                                      |             | FLWR  |                                  |             |
|  LEAD  | t_p->N-2 i=101                       |             | FLWR  |                                      |             | FLWR  |                                  |             |
|  LEAD  |                                      |             | CNDI  | N-1->t_p i=101                       | t=2         | FLWR  |                                  |             |
|  LEAD  |                                      |             | CNDI  | NEW ROLE                             |             | FLWR  |                                  |             |
|  LEAD  |                                      |             | CNDI  | t_pr->N-1 i=101ok={message.success}  |             | FLWR  |                                  |             |
|  LEAD  | N-2->t_pr i=101ok={message.success}  |             | CNDI  |                                      |             | FLWR  |                                  |             |
|  LEAD  |                                      |             | CNDI  | poll->N-1 t=2 li=101 lt=2            |             | FLWR  |                                  |             |
|  FLWR  | N-2->poll t=2 li=101 lt=2            | t=2         | CNDI  |                                      |             | FLWR  |                                  |             |
|  FLWR  | NEW ROLE                             |             | CNDI  |                                      |             | FLWR  |                                  |             |
|  FLWR  | vote->N-2 yes=True                   |             | CNDI  |                                      |             | FLWR  |                                  |             |
|  FLWR  |                                      |             | LEAD  | N-1->vote yes=True                   | lt=2 li=102 | FLWR  |                                  |             |
|  FLWR  |                                      |             | LEAD  | NEW ROLE                             |             | FLWR  |                                  |             |
|  FLWR  |                                      |             | LEAD  | poll->N-3 t=2 li=101 lt=2            |             | FLWR  |                                  |             |
|  FLWR  |                                      |             | LEAD  |                                      |             | FLWR  | N-2->poll t=2 li=101 lt=2        | t=2         |
|  FLWR  |                                      |             | LEAD  |                                      |             | FLWR  | vote->N-2 yes=True               |             |
|  FLWR  |                                      |             | LEAD  | N-3->vote yes=True                   |             | FLWR  |                                  |             |
|  FLWR  |                                      |             | LEAD  | ae->N-1 t=2 i=101 lt=1 e=1 c=101     |             | FLWR  |                                  |             |
|  FLWR  | N-2->ae t=2 i=101 lt=1 e=1 c=101     | lt=2 li=102 | LEAD  |                                      |             | FLWR  |                                  |             |
|  FLWR  | ae_reply->N-2 ok=True mi=102         |             | LEAD  |                                      |             | FLWR  |                                  |             |
|  FLWR  |                                      |             | LEAD  | N-1->ae_reply ok=True mi=102         | ci=102      | FLWR  |                                  |             |
|  FLWR  |                                      |             | LEAD  | ae->N-3 t=2 i=101 lt=1 e=1 c=101     |             | FLWR  |                                  |             |
|  FLWR  |                                      |             | LEAD  |                                      |             | FLWR  | N-2->ae t=2 i=101 lt=1 e=1 c=101 | lt=2 li=102 |
|  FLWR  |                                      |             | LEAD  |                                      |             | FLWR  | ae_reply->N-2 ok=True mi=102     |             |
|  FLWR  |                                      |             | LEAD  | N-3->ae_reply ok=True mi=102         |             | FLWR  |                                  |             |
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
** Node 1 has snapshot and empty log, {new_leader.uri} is leader, running command
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|  N-1   | N-1                              | N-1    | N-2   | N-2                              | N-2    | N-3   | N-3                              | N-3    | N-4  | N-4 | N-4   |
|  Role  | Op                               | Delta  | Role  | Op                               | Delta  | Role  | Op                               | Delta  | Role | Op  | Delta |
|  FLWR  |                                  |        | LEAD  | CMD START                        |        | FLWR  |                                  |        |
|  FLWR  |                                  |        | LEAD  | ae->N-1 t=2 i=102 lt=2 e=1 c=102 | li=103 | FLWR  |                                  |        |
|  FLWR  |                                  |        | LEAD  | ae->N-3 t=2 i=102 lt=2 e=1 c=102 |        | FLWR  |                                  |        |
|  FLWR  |                                  |        | LEAD  |                                  |        | FLWR  | N-2->ae t=2 i=102 lt=2 e=1 c=102 | li=103 |
|  FLWR  |                                  |        | LEAD  |                                  |        | FLWR  | ae_reply->N-2 ok=True mi=103     |        |
|  FLWR  | N-2->ae t=2 i=102 lt=2 e=1 c=102 | li=103 | LEAD  |                                  |        | FLWR  |                                  |        |
|  FLWR  | ae_reply->N-2 ok=True mi=103     |        | LEAD  |                                  |        | FLWR  |                                  |        |
|  FLWR  |                                  |        | LEAD  | N-3->ae_reply ok=True mi=103     | ci=103 | FLWR  |                                  |        |
|  FLWR  |                                  |        | LEAD  | N-1->ae_reply ok=True mi=103     |        | FLWR  |                                  |        |
|  FLWR  |                                  |        | LEAD  |                                  |        | FLWR  | N-2->ae t=2 i=103 lt=2 e=0 c=103 | ci=103 |
|  FLWR  |                                  |        | LEAD  | CMD DONE                         |        | FLWR  |                                  |        |
|  FLWR  | N-2->ae t=2 i=103 lt=2 e=0 c=103 | ci=103 | LEAD  |                                  |        | FLWR  |                                  |        |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
** Changing leader back to node 1 so that join will process snapshot
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|  N-1   | N-1                                  | N-1         | N-2   | N-2                              | N-2         | N-3   | N-3                              | N-3         | N-4   | N-4                                  | N-4                |
|  Role  | Op                                   | Delta       | Role  | Op                               | Delta       | Role  | Op                               | Delta       | Role  | Op                                   | Delta              |
|  FLWR  |                                      |             | FLWR  | NEW ROLE                         |             | FLWR  |                                  |             |
|  CNDI  | NEW ROLE                             | t=3         | FLWR  |                                  |             | FLWR  |                                  |             |
|  CNDI  | ae_reply->N-2 ok=True mi=103         |             | FLWR  |                                  |             | FLWR  |                                  |             |
|  CNDI  | poll->N-2 t=3 li=103 lt=3            |             | FLWR  |                                  |             | FLWR  |                                  |             |
|  CNDI  | poll->N-3 t=3 li=103 lt=3            |             | FLWR  |                                  |             | FLWR  |                                  |             |
|  CNDI  |                                      |             | FLWR  | N-1->ae_reply ok=True mi=103     |             | FLWR  |                                  |             |
|  CNDI  |                                      |             | FLWR  | N-1->poll t=3 li=103 lt=3        | t=3         | FLWR  |                                  |             |
|  CNDI  |                                      |             | FLWR  | vote->N-1 yes=True               |             | FLWR  |                                  |             |
|  CNDI  |                                      |             | FLWR  |                                  |             | FLWR  | ae_reply->N-2 ok=True mi=103     |             |
|  CNDI  |                                      |             | FLWR  |                                  |             | FLWR  | N-1->poll t=3 li=103 lt=3        | t=3         |
|  CNDI  |                                      |             | FLWR  |                                  |             | FLWR  | vote->N-1 yes=True               |             |
|  LEAD  | N-2->vote yes=True                   | lt=3 li=104 | FLWR  |                                  |             | FLWR  |                                  |             |
|  LEAD  | NEW ROLE                             |             | FLWR  |                                  |             | FLWR  |                                  |             |
|  LEAD  | N-3->vote yes=True                   |             | FLWR  |                                  |             | FLWR  |                                  |             |
|  LEAD  |                                      |             | FLWR  | N-3->ae_reply ok=True mi=103     |             | FLWR  |                                  |             |
|  LEAD  | ae->N-2 t=3 i=104 lt=3 e=0 c=103     |             | FLWR  |                                  |             | FLWR  |                                  |             |
|  LEAD  |                                      |             | FLWR  | N-1->ae t=3 i=104 lt=3 e=0 c=103 |             | FLWR  |                                  |             |
|  LEAD  |                                      |             | FLWR  | ae_reply->N-1 ok=False mi=103    |             | FLWR  |                                  |             |
|  LEAD  | N-2->ae_reply ok=False mi=103        |             | FLWR  |                                  |             | FLWR  |                                  |             |
|  LEAD  | ae->N-3 t=3 i=104 lt=3 e=0 c=103     |             | FLWR  |                                  |             | FLWR  |                                  |             |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  | N-1->ae t=3 i=104 lt=3 e=0 c=103 |             |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  | ae_reply->N-1 ok=False mi=103    |             |
|  LEAD  | N-3->ae_reply ok=False mi=103        |             | FLWR  |                                  |             | FLWR  |                                  |             |
|  LEAD  | ae->N-2 t=3 i=103 lt=2 e=1 c=103     |             | FLWR  |                                  |             | FLWR  |                                  |             |
|  LEAD  |                                      |             | FLWR  | N-1->ae t=3 i=103 lt=2 e=1 c=103 | lt=3 li=104 | FLWR  |                                  |             |
|  LEAD  |                                      |             | FLWR  | ae_reply->N-1 ok=True mi=104     |             | FLWR  |                                  |             |
|  LEAD  | N-2->ae_reply ok=True mi=104         | ci=104      | FLWR  |                                  |             | FLWR  |                                  |             |
|  LEAD  | ae->N-3 t=3 i=103 lt=2 e=1 c=103     |             | FLWR  |                                  |             | FLWR  |                                  |             |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  | N-1->ae t=3 i=103 lt=2 e=1 c=103 | lt=3 li=104 |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  | ae_reply->N-1 ok=True mi=104     |             |
|  LEAD  | N-3->ae_reply ok=True mi=104         |             | FLWR  |                                  |             | FLWR  |                                  |             |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  | m_c->N-1 op=ADD n=mcpy://4           |                    |
|  LEAD  | N-4->m_c op=ADD n=mcpy://4           |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  |                                      |                    |
|  LEAD  | ae->N-4 t=3 i=104 lt=3 e=0 c=104     |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  |                                      |                    |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  | N-1->ae t=3 i=104 lt=3 e=0 c=104     | t=3                |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  | ae_reply->N-1 ok=False mi=0          |                    |
|  LEAD  | N-4->ae_reply ok=False mi=0          |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  |                                      |                    |
|  LEAD  | sn->N-4 i=101                        |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  |                                      |                    |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  | N-1->sn i=101                        |                    |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  | snr->N-1 i=101s={message.success}    |                    |
|  LEAD  | N-4->snr i=101s={message.success}    |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  |                                      |                    |
|  LEAD  | sn->N-4 i=101                        |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  |                                      |                    |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  | N-1->sn i=101                        |                    |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  | snr->N-1 i=101s={message.success}    |                    |
|  LEAD  | N-4->snr i=101s={message.success}    |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  |                                      |                    |
|  LEAD  | sn->N-4 i=101                        |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  |                                      |                    |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  | N-1->sn i=101                        |                    |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  | snr->N-1 i=101s={message.success}    |                    |
|  LEAD  | N-4->snr i=101s={message.success}    |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  |                                      |                    |
|  LEAD  | sn->N-4 i=101                        |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  |                                      |                    |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  | N-1->sn i=101                        | ci=101             |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  | snr->N-1 i=101s={message.success}    |                    |
|  LEAD  | N-4->snr i=101s={message.success}    |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  |                                      |                    |
|  LEAD  | ae->N-4 t=3 i=104 lt=3 e=0 c=104     |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  |                                      |                    |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  | N-1->ae t=3 i=104 lt=3 e=0 c=104     |                    |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  | ae_reply->N-1 ok=False mi=101        |                    |
|  LEAD  | N-4->ae_reply ok=False mi=101        |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  |                                      |                    |
|  LEAD  | ae->N-4 t=3 i=101 lt=1 e=1 c=104     |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  |                                      |                    |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  | N-1->ae t=3 i=101 lt=1 e=1 c=104     | lt=2 li=102 ci=102 |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  | ae_reply->N-1 ok=True mi=102         |                    |
|  LEAD  | N-4->ae_reply ok=True mi=102         |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  |                                      |                    |
|  LEAD  | ae->N-4 t=3 i=102 lt=2 e=2 c=104     |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  |                                      |                    |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  | N-1->ae t=3 i=102 lt=2 e=2 c=104     | lt=3 li=104 ci=104 |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  | ae_reply->N-1 ok=True mi=104         |                    |
|  LEAD  | N-4->ae_reply ok=True mi=104         | li=105      | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  |                                      |                    |
|  LEAD  | ae->N-2 t=3 i=104 lt=3 e=1 c=104     |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  |                                      |                    |
|  LEAD  |                                      |             | FLWR  | N-1->ae t=3 i=104 lt=3 e=1 c=104 | li=105      | FLWR  |                                  |             | FLWR  |                                      |                    |
|  LEAD  |                                      |             | FLWR  | ae_reply->N-1 ok=True mi=105     |             | FLWR  |                                  |             | FLWR  |                                      |                    |
|  LEAD  | N-2->ae_reply ok=True mi=105         | ci=105      | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  |                                      |                    |
|  LEAD  | ae->N-3 t=3 i=104 lt=3 e=1 c=104     |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  |                                      |                    |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  | N-1->ae t=3 i=104 lt=3 e=1 c=104 | li=105      | FLWR  |                                      |                    |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  | ae_reply->N-1 ok=True mi=105     |             | FLWR  |                                      |                    |
|  LEAD  | N-3->ae_reply ok=True mi=105         |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  |                                      |                    |
|  LEAD  | m_cr->N-4 op=ADD n=mcpy://4 ok=True  |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  |                                      |                    |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  | N-1->m_cr op=ADD n=mcpy://4 ok=True  |                    |
|  LEAD  | ae->N-4 t=3 i=104 lt=3 e=1 c=104     |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  |                                      |                    |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  | N-1->ae t=3 i=104 lt=3 e=1 c=104     | li=105             |
|  LEAD  |                                      |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  | ae_reply->N-1 ok=True mi=105         |                    |
|  LEAD  | N-4->ae_reply ok=True mi=105         |             | FLWR  |                                  |             | FLWR  |                                  |             | FLWR  |                                      |                    |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


* Condensed Trace Table Legend
All the items in these legends labeled N-X are placeholders for actual node id values,
actual values will be N-1, N-2, N-3, etc. up to the number of nodes in the cluster. Yes, One based, not zero.

| Column Label | Description     | Details                                                                                        |
| N-X Role     | Raft Role       | FLWR = Follower CNDI = Candidate LEAD = Leader                                                 |
| N-X Op       | Activity        | Describes a traceable event at this node, see separate table below                             |
| N-X Delta    | State change    | Describes any change in state since previous trace, see separate table below                   |


** "Op" Column detail legend
| Value         | Meaning                                                                                      |
| STARTED       | Simulated node starting with empty log, term=0                                               |
| CMD START     | Simulated client requested that a node (usually leader, but not for all tests) run a command |
| CMD DONE      | The previous requested command is finished, whether complete, rejected, failed, whatever     |
| CRASH         | Simulating node has simulated a crash                                                        |
| RESTART       | Previously crashed node has restarted. Look at delta column to see effects on log, if any    |
| NEW ROLE      | The node has changed Raft role since last trace line                                         |
| NETSPLIT      | The node has been partitioned away from the majority network                                 |
| NETJOIN       | The node has rejoined the majority network                                                   |
| ae->N-X       | Node has sent append_entries message to N-X, next line in this table explains                |
| (continued)   | t=1 means current term is 1, i=1 means prevLogIndex=1, lt=1 means prevLogTerm=1              |
| (continued)   | c=1 means sender's commitIndex is 1,                                                         |
| (continued)   | e=2 means that the entries list in the message is 2 items long. eXo=0 is a heartbeat         |
| N-X->ae_reply | Node has received the response to an append_entries message, details in continued lines      |
| (continued)   | ok=(True or False) means that entries were saved or not, mi=3 says log max index = 3         |
| poll->N-X     | Node has sent request_vote to N-X, t=1 means current term is 1 (continued next line)         |
| (continued)   | li=0 means prevLogIndex = 0, lt=0 means prevLogTerm = 0                                      |
| N-X->vote     | Node has received request_vote response from N-X, yes=(True or False) indicates vote value   |
| p_v_r->N-X    | Node has sent pre_vote_request to N-X, t=1 means proposed term is 1 (continued next line)    |
| (continued)   | li=0 means prevLogIndex = 0, lt=0 means prevLogTerm = 0                                      |
| N-X->p_v      | Node has received pre_vote_response from N-X, yes=(True or False) indicates vote value       |
| m_c->N-X      | Node has sent memebership change to N-X op is add or remove and n is the node affected       |
| N-X->m_cr     | Node has received membership change response from N-X, ok indicates success value            |
| p_t->N-X      | Node has sent power transfer command N-X so node should assume power                         |
| N-X->p_tr     | Node has received power transfer response from N-X, ok indicates success value               |
| sn->N-X       | Node has sent snopshot copy command N-X so X node should apply it to local snapshot          |
| N-X>snr       | Node has received snapshot response from N-X, s indicates success value                      |

** "Delta" Column detail legend
Any item in this column indicates that the value of that item has changed since the last trace line

| Item | Meaning                                                                                                                         |
| t=X  | Term has changed to X                                                                                                           |
| lt=X | prevLogTerm has changed to X, indicating a log record has been stored                                                           |
| li=X | prevLogIndex has changed to X, indicating a log record has been stored                                                          |
| ci=X | Indicates commitIndex has changed to X, meaning log record has been committed, and possibly applied depending on type of record |
| n=X  | Indicates a change in networks status, X=1 means re-joined majority network, X=2 means partitioned to minority network          |

** Notes about interpreting traces
The way in which the traces are collected can occasionally obscure what is going on. A case in point is the commit of records at followers.
The commit process is triggered by an append_entries message arriving at the follower with a commitIndex value that exceeds the local
commit index, and that matches a record in the local log. This starts the commit process AFTER the response message is sent. You might
be expecting it to be prior to sending the response, in bound, as is often said. Whether this is expected behavior is not called out
as an element of the Raft protocol. It is certainly not required, however, as the follower doesn't report the commit index back to the
leader.

The definition of the commit state for a record is that a majority of nodes (leader and followers) have saved the record. Once
the leader detects this it applies and commits the record. At some point it will send another append_entries to the followers and they
will apply and commit. Or, if the leader dies before doing this, the next leader will commit by implication when it sends a term start
log record.

So when you are looking at the traces, you should not expect to see the commit index increas at a follower until some other message
traffic occurs, because the tracing function only checks the commit index at message transmission boundaries.






