* Test test_add_follower_too_many_rounds_1 from file tests/test_member_changes.py


    Tests that the membership change process will abort the add node process when the new node fails
    to catch up on all log records in 10 rounds of updates. This is accomplished by intercepting
    the append entries responses that indicate that the new node has finished appending the records
    for the current round ov updates and adding new records to the leader's log (and to the other followers)
    so that the leader starts another round. This is done until ten rounds have been completed, at which
    point the leader should abort the add. 
    Timers are disabled, so all timer driven operations such as heartbeats are manually triggered.
    


 *[[condensed Trace Table Legend][Table legend]] located after last table in file*

** Starting election at node 1 of 3
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|  N-1   | N-1                          | N-1       | N-2   | N-2                          | N-2       | N-3   | N-3                          | N-3       | N-4  | N-4 | N-4   |
|  Role  | Op                           | Delta     | Role  | Op                           | Delta     | Role  | Op                           | Delta     | Role | Op  | Delta |
|  FLWR  | STARTED                      |           | FLWR  | STARTED                      |           | FLWR  | STARTED                      |           |
|  CNDI  | NEW ROLE                     | t=1       | FLWR  |                              |           | FLWR  |                              |           |
|  CNDI  | poll->N-2 t=1 li=0 lt=1      |           | FLWR  |                              |           | FLWR  |                              |           |
|  CNDI  | poll->N-3 t=1 li=0 lt=1      |           | FLWR  |                              |           | FLWR  |                              |           |
|  CNDI  |                              |           | FLWR  | N-1->poll t=1 li=0 lt=1      | t=1       | FLWR  |                              |           |
|  CNDI  |                              |           | FLWR  | vote->N-1 yes=True           |           | FLWR  |                              |           |
|  CNDI  |                              |           | FLWR  |                              |           | FLWR  | N-1->poll t=1 li=0 lt=1      | t=1       |
|  CNDI  |                              |           | FLWR  |                              |           | FLWR  | vote->N-1 yes=True           |           |
|  LEAD  | N-2->vote yes=True           | lt=1 li=1 | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | NEW ROLE                     |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | ae->N-2 t=1 i=0 lt=0 e=1 c=0 |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | ae->N-3 t=1 i=0 lt=0 e=1 c=0 |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | N-3->vote yes=True           |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  |                              |           | FLWR  | N-1->ae t=1 i=0 lt=0 e=1 c=0 | lt=1 li=1 | FLWR  |                              |           |
|  LEAD  |                              |           | FLWR  | ae_reply->N-1 ok=True mi=1   |           | FLWR  |                              |           |
|  LEAD  |                              |           | FLWR  |                              |           | FLWR  | N-1->ae t=1 i=0 lt=0 e=1 c=0 | lt=1 li=1 |
|  LEAD  |                              |           | FLWR  |                              |           | FLWR  | ae_reply->N-1 ok=True mi=1   |           |
|  LEAD  | N-2->ae_reply ok=True mi=1   | ci=1      | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | N-3->ae_reply ok=True mi=1   |           | FLWR  |                              |           | FLWR  |                              |           |
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
** Node 1 is leader, inserting some records via direct acceess to logs
-----------------------------------------------------------------------------------------------------------------------------------------------------
|  N-1   | N-1                          | N-1   | N-2   | N-2 | N-2   | N-3   | N-3 | N-3   | N-4   | N-4                          | N-4            |
|  Role  | Op                           | Delta | Role  | Op  | Delta | Role  | Op  | Delta | Role  | Op                           | Delta          |
|  LEAD  |                              |       | FLWR  |     |       | FLWR  |     |       | FLWR  | m_c->N-1 op=ADD n=mcpy://4   |                |
|  LEAD  | N-4->m_c op=ADD n=mcpy://4   |       | FLWR  |     |       | FLWR  |     |       | FLWR  |                              |                |
|  LEAD  | ae->N-4 t=1 i=7 lt=1 e=0 c=7 |       | FLWR  |     |       | FLWR  |     |       | FLWR  |                              |                |
|  LEAD  |                              |       | FLWR  |     |       | FLWR  |     |       | FLWR  | N-1->ae t=1 i=7 lt=1 e=0 c=7 | t=1            |
|  LEAD  | N-4->ae_reply ok=False mi=0  |       | FLWR  |     |       | FLWR  |     |       | FLWR  |                              |                |
|  LEAD  | ae->N-4 t=1 i=0 lt=0 e=1 c=7 |       | FLWR  |     |       | FLWR  |     |       | FLWR  |                              |                |
|  LEAD  |                              |       | FLWR  |     |       | FLWR  |     |       | FLWR  | N-1->ae t=1 i=0 lt=0 e=1 c=7 | lt=1 li=1 ci=1 |
|  LEAD  |                              |       | FLWR  |     |       | FLWR  |     |       | FLWR  | ae_reply->N-1 ok=True mi=1   |                |
|  LEAD  | N-4->ae_reply ok=True mi=1   |       | FLWR  |     |       | FLWR  |     |       | FLWR  |                              |                |
|  LEAD  | ae->N-4 t=1 i=1 lt=1 e=6 c=7 |       | FLWR  |     |       | FLWR  |     |       | FLWR  |                              |                |
|  LEAD  |                              |       | FLWR  |     |       | FLWR  |     |       | FLWR  | N-1->ae t=1 i=1 lt=1 e=6 c=7 | li=7 ci=7      |
-----------------------------------------------------------------------------------------------------------------------------------------------------
** Starting a loop of round update and inserted new rounds
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|  N-1   | N-1                                   | N-1         | N-2   | N-2 | N-2   | N-3   | N-3 | N-3   | N-4   | N-4                                   | N-4         |
|  Role  | Op                                    | Delta       | Role  | Op  | Delta | Role  | Op  | Delta | Role  | Op                                    | Delta       |
|  LEAD  |                                       |             | FLWR  |     |       | FLWR  |     |       | FLWR  | ae_reply->N-1 ok=True mi=7            |             |
|  LEAD  | N-4->ae_reply ok=True mi=7            |             | FLWR  |     |       | FLWR  |     |       | FLWR  |                                       |             |
|  LEAD  | ae->N-4 t=1 i=7 lt=1 e=1 c=8          |             | FLWR  |     |       | FLWR  |     |       | FLWR  |                                       |             |
|  LEAD  |                                       |             | FLWR  |     |       | FLWR  |     |       | FLWR  | N-1->ae t=1 i=7 lt=1 e=1 c=8          | li=8 ci=8   |
|  LEAD  |                                       | li=9 ci=9   | FLWR  |     |       | FLWR  |     |       | FLWR  | ae_reply->N-1 ok=True mi=8            |             |
|  LEAD  | N-4->ae_reply ok=True mi=8            |             | FLWR  |     |       | FLWR  |     |       | FLWR  |                                       |             |
|  LEAD  | ae->N-4 t=1 i=8 lt=1 e=1 c=9          |             | FLWR  |     |       | FLWR  |     |       | FLWR  |                                       |             |
|  LEAD  |                                       |             | FLWR  |     |       | FLWR  |     |       | FLWR  | N-1->ae t=1 i=8 lt=1 e=1 c=9          | li=9 ci=9   |
|  LEAD  |                                       | li=10 ci=10 | FLWR  |     |       | FLWR  |     |       | FLWR  | ae_reply->N-1 ok=True mi=9            |             |
|  LEAD  | N-4->ae_reply ok=True mi=9            |             | FLWR  |     |       | FLWR  |     |       | FLWR  |                                       |             |
|  LEAD  | ae->N-4 t=1 i=9 lt=1 e=1 c=10         |             | FLWR  |     |       | FLWR  |     |       | FLWR  |                                       |             |
|  LEAD  |                                       |             | FLWR  |     |       | FLWR  |     |       | FLWR  | N-1->ae t=1 i=9 lt=1 e=1 c=10         | li=10 ci=10 |
|  LEAD  |                                       | li=11 ci=11 | FLWR  |     |       | FLWR  |     |       | FLWR  | ae_reply->N-1 ok=True mi=10           |             |
|  LEAD  | N-4->ae_reply ok=True mi=10           |             | FLWR  |     |       | FLWR  |     |       | FLWR  |                                       |             |
|  LEAD  | ae->N-4 t=1 i=10 lt=1 e=1 c=11        |             | FLWR  |     |       | FLWR  |     |       | FLWR  |                                       |             |
|  LEAD  |                                       |             | FLWR  |     |       | FLWR  |     |       | FLWR  | N-1->ae t=1 i=10 lt=1 e=1 c=11        | li=11 ci=11 |
|  LEAD  |                                       | li=12 ci=12 | FLWR  |     |       | FLWR  |     |       | FLWR  | ae_reply->N-1 ok=True mi=11           |             |
|  LEAD  | N-4->ae_reply ok=True mi=11           |             | FLWR  |     |       | FLWR  |     |       | FLWR  |                                       |             |
|  LEAD  | ae->N-4 t=1 i=11 lt=1 e=1 c=12        |             | FLWR  |     |       | FLWR  |     |       | FLWR  |                                       |             |
|  LEAD  |                                       |             | FLWR  |     |       | FLWR  |     |       | FLWR  | N-1->ae t=1 i=11 lt=1 e=1 c=12        | li=12 ci=12 |
|  LEAD  |                                       | li=13 ci=13 | FLWR  |     |       | FLWR  |     |       | FLWR  | ae_reply->N-1 ok=True mi=12           |             |
|  LEAD  | N-4->ae_reply ok=True mi=12           |             | FLWR  |     |       | FLWR  |     |       | FLWR  |                                       |             |
|  LEAD  | ae->N-4 t=1 i=12 lt=1 e=1 c=13        |             | FLWR  |     |       | FLWR  |     |       | FLWR  |                                       |             |
|  LEAD  |                                       |             | FLWR  |     |       | FLWR  |     |       | FLWR  | N-1->ae t=1 i=12 lt=1 e=1 c=13        | li=13 ci=13 |
|  LEAD  |                                       | li=14 ci=14 | FLWR  |     |       | FLWR  |     |       | FLWR  | ae_reply->N-1 ok=True mi=13           |             |
|  LEAD  | N-4->ae_reply ok=True mi=13           |             | FLWR  |     |       | FLWR  |     |       | FLWR  |                                       |             |
|  LEAD  | ae->N-4 t=1 i=13 lt=1 e=1 c=14        |             | FLWR  |     |       | FLWR  |     |       | FLWR  |                                       |             |
|  LEAD  |                                       |             | FLWR  |     |       | FLWR  |     |       | FLWR  | N-1->ae t=1 i=13 lt=1 e=1 c=14        | li=14 ci=14 |
|  LEAD  |                                       | li=15 ci=15 | FLWR  |     |       | FLWR  |     |       | FLWR  | ae_reply->N-1 ok=True mi=14           |             |
|  LEAD  | N-4->ae_reply ok=True mi=14           |             | FLWR  |     |       | FLWR  |     |       | FLWR  |                                       |             |
|  LEAD  | ae->N-4 t=1 i=14 lt=1 e=1 c=15        |             | FLWR  |     |       | FLWR  |     |       | FLWR  |                                       |             |
|  LEAD  |                                       |             | FLWR  |     |       | FLWR  |     |       | FLWR  | N-1->ae t=1 i=14 lt=1 e=1 c=15        | li=15 ci=15 |
|  LEAD  |                                       | li=16 ci=16 | FLWR  |     |       | FLWR  |     |       | FLWR  | ae_reply->N-1 ok=True mi=15           |             |
|  LEAD  | N-4->ae_reply ok=True mi=15           |             | FLWR  |     |       | FLWR  |     |       | FLWR  |                                       |             |
|  LEAD  | ae->N-4 t=1 i=15 lt=1 e=1 c=16        |             | FLWR  |     |       | FLWR  |     |       | FLWR  |                                       |             |
|  LEAD  |                                       |             | FLWR  |     |       | FLWR  |     |       | FLWR  | N-1->ae t=1 i=15 lt=1 e=1 c=16        | li=16 ci=16 |
|  LEAD  |                                       | li=17 ci=17 | FLWR  |     |       | FLWR  |     |       | FLWR  | ae_reply->N-1 ok=True mi=16           |             |
|  LEAD  | N-4->ae_reply ok=True mi=16           |             | FLWR  |     |       | FLWR  |     |       | FLWR  |                                       |             |
|  LEAD  | m_cr->N-4 op=ADD n=mcpy://4 ok=False  |             | FLWR  |     |       | FLWR  |     |       | FLWR  |                                       |             |
|  LEAD  |                                       |             | FLWR  |     |       | FLWR  |     |       | FLWR  | N-1->m_cr op=ADD n=mcpy://4 ok=False  |             |
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------


* Condensed Trace Table Legend
All the items in these legends labeled N-X are placeholders for actual node id values,
actual values will be N-1, N-2, N-3, etc. up to the number of nodes in the cluster. Yes, One based, not zero.

| Column Label | Description     | Details                                                                                        |
| N-X Role     | Raft Role       | FLWR = Follower CNDI = Candidate LEAD = Leader                                                 |
| N-X Op       | Activity        | Describes a traceable event at this node, see separate table below                             |
| N-X Delta    | State change    | Describes any change in state since previous trace, see separate table below                   |


** "Op" Column detail legend
| Value         | Meaning                                                                                      |
| STARTED       | Simulated node starting with empty log, term=0                                               |
| CMD START     | Simulated client requested that a node (usually leader, but not for all tests) run a command |
| CMD DONE      | The previous requested command is finished, whether complete, rejected, failed, whatever     |
| CRASH         | Simulating node has simulated a crash                                                        |
| RESTART       | Previously crashed node has restarted. Look at delta column to see effects on log, if any    |
| NEW ROLE      | The node has changed Raft role since last trace line                                         |
| NETSPLIT      | The node has been partitioned away from the majority network                                 |
| NETJOIN       | The node has rejoined the majority network                                                   |
| ae->N-X       | Node has sent append_entries message to N-X, next line in this table explains                |
| (continued)   | t=1 means current term is 1, i=1 means prevLogIndex=1, lt=1 means prevLogTerm=1              |
| (continued)   | c=1 means sender's commitIndex is 1,                                                         |
| (continued)   | e=2 means that the entries list in the message is 2 items long. eXo=0 is a heartbeat         |
| N-X->ae_reply | Node has received the response to an append_entries message, details in continued lines      |
| (continued)   | ok=(True or False) means that entries were saved or not, mi=3 says log max index = 3         |
| poll->N-X     | Node has sent request_vote to N-X, t=1 means current term is 1 (continued next line)         |
| (continued)   | li=0 means prevLogIndex = 0, lt=0 means prevLogTerm = 0                                      |
| N-X->vote     | Node has received request_vote response from N-X, yes=(True or False) indicates vote value   |
| p_v_r->N-X    | Node has sent pre_vote_request to N-X, t=1 means proposed term is 1 (continued next line)    |
| (continued)   | li=0 means prevLogIndex = 0, lt=0 means prevLogTerm = 0                                      |
| N-X->p_v      | Node has received pre_vote_response from N-X, yes=(True or False) indicates vote value       |
| m_c->N-X      | Node has sent memebership change to N-X op is add or remove and n is the node affected       |
| N-X->m_cr     | Node has received membership change response from N-X, ok indicates success value            |
| p_t->N-X      | Node has sent power transfer command N-X so node should assume power                         |
| N-X->p_tr     | Node has received power transfer response from N-X, ok indicates success value               |

** "Delta" Column detail legend
Any item in this column indicates that the value of that item has changed since the last trace line

| Item | Meaning                                                                                                                         |
| t=X  | Term has changed to X                                                                                                           |
| lt=X | prevLogTerm has changed to X, indicating a log record has been stored                                                           |
| li=X | prevLogIndex has changed to X, indicating a log record has been stored                                                          |
| ci=X | Indicates commitIndex has changed to X, meaning log record has been committed, and possibly applied depending on type of record |
| n=X  | Indicates a change in networks status, X=1 means re-joined majority network, X=2 means partitioned to minority network          |

** Notes about interpreting traces
The way in which the traces are collected can occasionally obscure what is going on. A case in point is the commit of records at followers.
The commit process is triggered by an append_entries message arriving at the follower with a commitIndex value that exceeds the local
commit index, and that matches a record in the local log. This starts the commit process AFTER the response message is sent. You might
be expecting it to be prior to sending the response, in bound, as is often said. Whether this is expected behavior is not called out
as an element of the Raft protocol. It is certainly not required, however, as the follower doesn't report the commit index back to the
leader.

The definition of the commit state for a record is that a majority of nodes (leader and followers) have saved the record. Once
the leader detects this it applies and commits the record. At some point it will send another append_entries to the followers and they
will apply and commit. Or, if the leader dies before doing this, the next leader will commit by implication when it sends a term start
log record.

So when you are looking at the traces, you should not expect to see the commit index increas at a follower until some other message
traffic occurs, because the tracing function only checks the commit index at message transmission boundaries.






