* Test test_partition_1 from file tests/test_partition_1.py


    This is a basic test of network partitioning and recovery. Five nodes are
    started and brought into sync after and election. Then two nodes are
    configured to be on a different simulated network partition than the
    leader and two other nodes. This means that the leader still has a quorum
    and can continue to advance the log. So, the leader runs a couple of commands
    after partition and we check to see that the reachable nodes get updated
    properly. We also check that the unreachable ones don't, but that is more
    about testing the simulation rather than any raft feature.

    One these verifications are done, the isolated nodes are configured to rejoin
    the main network and the leader is prodded to do a heartbeat broadcast. Some
    fiddly simulation control bits are used to single step through the message
    delivery process so as to verify that each heartbeat message reaches
    the right target and the target does the correct state ops and encodes
    the right reply. The rejoined nodes should walk through the state changes
    until they have correctly replicated the leader's log and the simulation
    state machine's final state.

    Timers are disabled, so all timer driven operations such as heartbeats are manually triggered.
    


 *[[condensed Trace Table Legend][Table legend]] located after last table in file*

** Initial election, normal
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|  N-1   | N-1                          | N-1       | N-2   | N-2                          | N-2       | N-3   | N-3                          | N-3       | N-4   | N-4                          | N-4       | N-5   | N-5                          | N-5       |
|  Role  | Op                           | Delta     | Role  | Op                           | Delta     | Role  | Op                           | Delta     | Role  | Op                           | Delta     | Role  | Op                           | Delta     |
|  FLWR  | STARTED                      |           | FLWR  | STARTED                      |           | FLWR  | STARTED                      |           | FLWR  | STARTED                      |           | FLWR  | STARTED                      |           |
|  CNDI  | NEW ROLE                     | t=1       | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           |
|  CNDI  | poll->N-2 t=1 li=0 lt=1      |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           |
|  CNDI  | poll->N-3 t=1 li=0 lt=1      |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           |
|  CNDI  | poll->N-4 t=1 li=0 lt=1      |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           |
|  CNDI  | poll->N-5 t=1 li=0 lt=1      |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           |
|  CNDI  |                              |           | FLWR  | N-1->poll t=1 li=0 lt=1      |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           |
|  CNDI  |                              |           | FLWR  | vote->N-1 yes=True           | t=1       | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           |
|  CNDI  |                              |           | FLWR  |                              |           | FLWR  | N-1->poll t=1 li=0 lt=1      |           | FLWR  |                              |           | FLWR  |                              |           |
|  CNDI  |                              |           | FLWR  |                              |           | FLWR  | vote->N-1 yes=True           | t=1       | FLWR  |                              |           | FLWR  |                              |           |
|  CNDI  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  | N-1->poll t=1 li=0 lt=1      |           | FLWR  |                              |           |
|  CNDI  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  | vote->N-1 yes=True           | t=1       | FLWR  |                              |           |
|  CNDI  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  | N-1->poll t=1 li=0 lt=1      |           |
|  CNDI  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  | vote->N-1 yes=True           | t=1       |
|  CNDI  | N-2->vote yes=True           |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           |
|  CNDI  | N-3->vote yes=True           |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | NEW ROLE                     | lt=1 li=1 | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | ae->N-2 t=1 i=0 lt=0 e=1 c=0 |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | ae->N-3 t=1 i=0 lt=0 e=1 c=0 |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | ae->N-4 t=1 i=0 lt=0 e=1 c=0 |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | ae->N-5 t=1 i=0 lt=0 e=1 c=0 |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | N-4->vote yes=True           |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | N-5->vote yes=True           |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  |                              |           | FLWR  | N-1->ae t=1 i=0 lt=0 e=1 c=0 |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  |                              |           | FLWR  | ae_reply->N-1 ok=True mi=1   | lt=1 li=1 | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  |                              |           | FLWR  |                              |           | FLWR  | N-1->ae t=1 i=0 lt=0 e=1 c=0 |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  |                              |           | FLWR  |                              |           | FLWR  | ae_reply->N-1 ok=True mi=1   | lt=1 li=1 | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  | N-1->ae t=1 i=0 lt=0 e=1 c=0 |           | FLWR  |                              |           |
|  LEAD  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  | ae_reply->N-1 ok=True mi=1   | lt=1 li=1 | FLWR  |                              |           |
|  LEAD  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  | N-1->ae t=1 i=0 lt=0 e=1 c=0 |           |
|  LEAD  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  | ae_reply->N-1 ok=True mi=1   | lt=1 li=1 |
|  LEAD  | N-2->ae_reply ok=True mi=1   |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | N-3->ae_reply ok=True mi=1   |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | N-4->ae_reply ok=True mi=1   | ci=1      | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | N-5->ae_reply ok=True mi=1   |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           | FLWR  |                              |           |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
** Run one command, normal sequence till leader commit, check follower's final state
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|  N-1   | N-1                          | N-1   | N-2   | N-2                          | N-2   | N-3   | N-3                          | N-3   | N-4   | N-4                          | N-4   | N-5   | N-5                          | N-5   |
|  Role  | Op                           | Delta | Role  | Op                           | Delta | Role  | Op                           | Delta | Role  | Op                           | Delta | Role  | Op                           | Delta |
|  LEAD  | CMD START                    |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | ae->N-2 t=1 i=1 lt=1 e=1 c=1 | li=2  | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | ae->N-3 t=1 i=1 lt=1 e=1 c=1 |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | ae->N-4 t=1 i=1 lt=1 e=1 c=1 |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | ae->N-5 t=1 i=1 lt=1 e=1 c=1 |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  | N-1->ae t=1 i=1 lt=1 e=1 c=1 |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  | ae_reply->N-1 ok=True mi=2   | li=2  | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |                              |       | FLWR  | N-1->ae t=1 i=1 lt=1 e=1 c=1 |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |                              |       | FLWR  | ae_reply->N-1 ok=True mi=2   | li=2  | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  | N-1->ae t=1 i=1 lt=1 e=1 c=1 |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  | ae_reply->N-1 ok=True mi=2   | li=2  | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  | N-1->ae t=1 i=1 lt=1 e=1 c=1 |       |
|  LEAD  |                              |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  | ae_reply->N-1 ok=True mi=2   | li=2  |
|  LEAD  | N-2->ae_reply ok=True mi=2   |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | N-3->ae_reply ok=True mi=2   |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | N-4->ae_reply ok=True mi=2   | ci=2  | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | N-5->ae_reply ok=True mi=2   |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  | N-1->ae t=1 i=2 lt=1 e=0 c=2 |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |                              | ci=2  | FLWR  | N-1->ae t=1 i=2 lt=1 e=0 c=2 |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |                              |       | FLWR  |                              | ci=2  | FLWR  | N-1->ae t=1 i=2 lt=1 e=0 c=2 |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              | ci=2  | FLWR  | N-1->ae t=1 i=2 lt=1 e=0 c=2 |       |
|  LEAD  | CMD DONE                     |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              | ci=2  |
|  LEAD  |                              |       | FLWR  | ae_reply->N-1 ok=True mi=2   |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |                              |       | FLWR  | ae_reply->N-1 ok=True mi=2   |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  | ae_reply->N-1 ok=True mi=2   |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  | ae_reply->N-1 ok=True mi=2   |       |
|  LEAD  | N-2->ae_reply ok=True mi=2   |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | N-3->ae_reply ok=True mi=2   |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | N-4->ae_reply ok=True mi=2   |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | N-5->ae_reply ok=True mi=2   |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       | FLWR  |                              |       |
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
** Partitioning the network to isolate nodes 2 and 3
----------------------------------------------------------------------------------------------------------------------------
|  N-1   | N-1 | N-1   | N-2   | N-2       | N-2   | N-3   | N-3       | N-3   | N-4   | N-4 | N-4   | N-5   | N-5 | N-5   |
|  Role  | Op  | Delta | Role  | Op        | Delta | Role  | Op        | Delta | Role  | Op  | Delta | Role  | Op  | Delta |
|  LEAD  |     |       | FLWR  | NETSPLIT  |       | FLWR  |           |       | FLWR  |     |       | FLWR  |     |       |
|  LEAD  |     |       | FLWR  |           | n=2   | FLWR  | NETSPLIT  | n=2   | FLWR  |     |       | FLWR  |     |       |
----------------------------------------------------------------------------------------------------------------------------
** Running two commands, only nodes 1, 4 and 5 should participate
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|  N-1   | N-1                          | N-1   | N-2   | N-2 | N-2   | N-3   | N-3 | N-3   | N-4   | N-4                          | N-4   | N-5   | N-5                          | N-5   |
|  Role  | Op                           | Delta | Role  | Op  | Delta | Role  | Op  | Delta | Role  | Op                           | Delta | Role  | Op                           | Delta |
|  LEAD  | CMD START                    |       | FLWR  |     |       | FLWR  |     |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | ae->N-4 t=1 i=2 lt=1 e=1 c=2 | li=3  | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | ae->N-5 t=1 i=2 lt=1 e=1 c=2 |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  | N-1->ae t=1 i=2 lt=1 e=1 c=2 |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  | ae_reply->N-1 ok=True mi=3   | li=3  | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |                              |       | FLWR  | N-1->ae t=1 i=2 lt=1 e=1 c=2 |       |
|  LEAD  |                              |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |                              |       | FLWR  | ae_reply->N-1 ok=True mi=3   | li=3  |
|  LEAD  | N-4->ae_reply ok=True mi=3   |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | N-5->ae_reply ok=True mi=3   |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  |                              | ci=3  | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  | N-1->ae t=1 i=3 lt=1 e=0 c=3 |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |                              | ci=3  | FLWR  | N-1->ae t=1 i=3 lt=1 e=0 c=3 |       |
|  LEAD  | CMD DONE                     |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |                              |       | FLWR  |                              | ci=3  |
|  LEAD  |                              |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  | ae_reply->N-1 ok=True mi=3   |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |                              |       | FLWR  | ae_reply->N-1 ok=True mi=3   |       |
|  LEAD  | N-4->ae_reply ok=True mi=3   |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | N-5->ae_reply ok=True mi=3   |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | CMD START                    |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | ae->N-4 t=1 i=3 lt=1 e=1 c=3 | li=4  | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | ae->N-5 t=1 i=3 lt=1 e=1 c=3 |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  | N-1->ae t=1 i=3 lt=1 e=1 c=3 |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  | ae_reply->N-1 ok=True mi=4   | li=4  | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |                              |       | FLWR  | N-1->ae t=1 i=3 lt=1 e=1 c=3 |       |
|  LEAD  |                              |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |                              |       | FLWR  | ae_reply->N-1 ok=True mi=4   | li=4  |
|  LEAD  | N-4->ae_reply ok=True mi=4   |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | N-5->ae_reply ok=True mi=4   |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  |                              | ci=4  | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  | N-1->ae t=1 i=4 lt=1 e=0 c=4 |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |                              | ci=4  | FLWR  | N-1->ae t=1 i=4 lt=1 e=0 c=4 |       |
|  LEAD  | CMD DONE                     |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |                              |       | FLWR  |                              | ci=4  |
|  LEAD  |                              |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  | ae_reply->N-1 ok=True mi=4   |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |                              |       | FLWR  | ae_reply->N-1 ok=True mi=4   |       |
|  LEAD  | N-4->ae_reply ok=True mi=4   |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | N-5->ae_reply ok=True mi=4   |       | FLWR  |     | n=2   | FLWR  |     | n=2   | FLWR  |                              |       | FLWR  |                              |       |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
** Healing network, nodes 2 and 3 will now be reachable from leader node 1, sending heartbeats
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|  N-1   | N-1                          | N-1   | N-2   | N-2      | N-2   | N-3   | N-3      | N-3   | N-4   | N-4                          | N-4   | N-5   | N-5                          | N-5   |
|  Role  | Op                           | Delta | Role  | Op       | Delta | Role  | Op       | Delta | Role  | Op                           | Delta | Role  | Op                           | Delta |
|  LEAD  |                              |       | FLWR  | NETJOIN  | n=1   | FLWR  |          |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |          |       | FLWR  | NETJOIN  | n=1   | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | ae->N-2 t=1 i=4 lt=1 e=0 c=4 |       | FLWR  |          |       | FLWR  |          |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | ae->N-3 t=1 i=4 lt=1 e=0 c=4 |       | FLWR  |          |       | FLWR  |          |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | ae->N-4 t=1 i=4 lt=1 e=0 c=4 |       | FLWR  |          |       | FLWR  |          |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | ae->N-5 t=1 i=4 lt=1 e=0 c=4 |       | FLWR  |          |       | FLWR  |          |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |          |       | FLWR  |          |       | FLWR  | N-1->ae t=1 i=4 lt=1 e=0 c=4 |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |          |       | FLWR  |          |       | FLWR  | ae_reply->N-1 ok=True mi=4   |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |          |       | FLWR  |          |       | FLWR  |                              |       | FLWR  | N-1->ae t=1 i=4 lt=1 e=0 c=4 |       |
|  LEAD  |                              |       | FLWR  |          |       | FLWR  |          |       | FLWR  |                              |       | FLWR  | ae_reply->N-1 ok=True mi=4   |       |
|  LEAD  | N-4->ae_reply ok=True mi=4   |       | FLWR  |          |       | FLWR  |          |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | N-5->ae_reply ok=True mi=4   |       | FLWR  |          |       | FLWR  |          |       | FLWR  |                              |       | FLWR  |                              |       |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
** Nodes 4 and 5 have processed heartbeats, now nodes 2 and 3 should do so
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|  N-1   | N-1                          | N-1   | N-2   | N-2                          | N-2       | N-3   | N-3                          | N-3       | N-4   | N-4 | N-4   | N-5   | N-5 | N-5   |
|  Role  | Op                           | Delta | Role  | Op                           | Delta     | Role  | Op                           | Delta     | Role  | Op  | Delta | Role  | Op  | Delta |
|  LEAD  |                              |       | FLWR  | N-1->ae t=1 i=4 lt=1 e=0 c=4 |           | FLWR  |                              |           | FLWR  |     |       | FLWR  |     |       |
|  LEAD  |                              |       | FLWR  | ae_reply->N-1 ok=False mi=2  |           | FLWR  |                              |           | FLWR  |     |       | FLWR  |     |       |
|  LEAD  | N-2->ae_reply ok=False mi=2  |       | FLWR  |                              |           | FLWR  |                              |           | FLWR  |     |       | FLWR  |     |       |
|  LEAD  | ae->N-2 t=1 i=2 lt=1 e=1 c=4 |       | FLWR  |                              |           | FLWR  |                              |           | FLWR  |     |       | FLWR  |     |       |
|  LEAD  |                              |       | FLWR  | N-1->ae t=1 i=2 lt=1 e=1 c=4 |           | FLWR  |                              |           | FLWR  |     |       | FLWR  |     |       |
|  LEAD  |                              |       | FLWR  | ae_reply->N-1 ok=True mi=3   | li=3 ci=3 | FLWR  |                              |           | FLWR  |     |       | FLWR  |     |       |
|  LEAD  | N-2->ae_reply ok=True mi=3   |       | FLWR  |                              |           | FLWR  |                              |           | FLWR  |     |       | FLWR  |     |       |
|  LEAD  | ae->N-2 t=1 i=3 lt=1 e=1 c=4 |       | FLWR  |                              |           | FLWR  |                              |           | FLWR  |     |       | FLWR  |     |       |
|  LEAD  |                              |       | FLWR  | N-1->ae t=1 i=3 lt=1 e=1 c=4 |           | FLWR  |                              |           | FLWR  |     |       | FLWR  |     |       |
|  LEAD  |                              |       | FLWR  | ae_reply->N-1 ok=True mi=4   | li=4 ci=4 | FLWR  |                              |           | FLWR  |     |       | FLWR  |     |       |
|  LEAD  | N-2->ae_reply ok=True mi=4   |       | FLWR  |                              |           | FLWR  |                              |           | FLWR  |     |       | FLWR  |     |       |
|  LEAD  |                              |       | FLWR  |                              |           | FLWR  | N-1->ae t=1 i=4 lt=1 e=0 c=4 |           | FLWR  |     |       | FLWR  |     |       |
|  LEAD  |                              |       | FLWR  |                              |           | FLWR  | ae_reply->N-1 ok=False mi=2  |           | FLWR  |     |       | FLWR  |     |       |
|  LEAD  | N-3->ae_reply ok=False mi=2  |       | FLWR  |                              |           | FLWR  |                              |           | FLWR  |     |       | FLWR  |     |       |
|  LEAD  | ae->N-3 t=1 i=2 lt=1 e=1 c=4 |       | FLWR  |                              |           | FLWR  |                              |           | FLWR  |     |       | FLWR  |     |       |
|  LEAD  |                              |       | FLWR  |                              |           | FLWR  | N-1->ae t=1 i=2 lt=1 e=1 c=4 |           | FLWR  |     |       | FLWR  |     |       |
|  LEAD  |                              |       | FLWR  |                              |           | FLWR  | ae_reply->N-1 ok=True mi=3   | li=3 ci=3 | FLWR  |     |       | FLWR  |     |       |
|  LEAD  | N-3->ae_reply ok=True mi=3   |       | FLWR  |                              |           | FLWR  |                              |           | FLWR  |     |       | FLWR  |     |       |
|  LEAD  | ae->N-3 t=1 i=3 lt=1 e=1 c=4 |       | FLWR  |                              |           | FLWR  |                              |           | FLWR  |     |       | FLWR  |     |       |
|  LEAD  |                              |       | FLWR  |                              |           | FLWR  | N-1->ae t=1 i=3 lt=1 e=1 c=4 |           | FLWR  |     |       | FLWR  |     |       |
|  LEAD  |                              |       | FLWR  |                              |           | FLWR  | ae_reply->N-1 ok=True mi=4   | li=4 ci=4 | FLWR  |     |       | FLWR  |     |       |
|  LEAD  | N-3->ae_reply ok=True mi=4   |       | FLWR  |                              |           | FLWR  |                              |           | FLWR  |     |       | FLWR  |     |       |
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


* Condensed Trace Table Legend
All the items in these legends labeled N-X are placeholders for actual node id values,
actual values will be N-1, N-2, N-3, etc. up to the number of nodes in the cluster. Yes, One based, not zero.

| Column Label | Description     | Details                                                                                        |
| N-X Role     | Raft Role       | FLWR = Follower CNDI = Candidate LEAD = Leader                                                 |
| N-X Op       | Activity        | Describes a traceable event at this node, see separate table below                             |
| N-X Delta    | State change    | Describes any change in state since previous trace, see separate table below                   |


** "Op" Column detail legend
| Value         | Meaning                                                                                      |
| STARTED       | Simulated node starting with empty log, term=0                                               |
| CMD START     | Simulated client requested that a node (usually leader, but not for all tests) run a command |
| CMD DONE      | The previous requested command is finished, whether complete, rejected, failed, whatever     |
| CRASH         | Simulating node has simulated a crash                                                        |
| RESTART       | Previously crashed node has restarted. Look at delta column to see effects on log, if any    |
| NEW ROLE      | The node has changed Raft role since last trace line                                         |
| NETSPLIT      | The node has been partitioned away from the majority network                                 |
| NETJOIN       | The node has rejoined the majority network                                                   |
| ae->N-X       | Node has sent append_entries message to N-X, next line in this table explains                |
| (continued)   | t=1 means current term is 1, i=1 means prevLogIndex=1, lt=1 means prevLogTerm=1              |
| (continued)   | c=1 means sender's commitIndex is 1,                                                         |
| (continued)   | e=2 means that the entries list in the message is 2 items long. eXo=0 is a heartbeat         |
| N-X->ae_reply | Node has received the response to an append_entries message, details in continued lines      |
| (continued)   | ok=(True or False) means that entries were saved or not, mi=3 says log max index = 3         |
| do_vote->N-X  | Node has sent request_vote to N-X, t=1 means current term is 1 (continued next line)         |
| (continued)   | li=0 means prevLogIndex = 0, lt=0 means prevLogTerm = 0                                      |
| N-X->vote     | Node has received request_vote response from N-X, yes=(True or False) indicates vote value   |

** "Delta" Column detail legend
Any item in this column indicates that the value of that item has changed since the last trace line

| Item | Meaning                                                                                                                         |
| t=X  | Term has changed to X                                                                                                           |
| lt=X | prevLogTerm has changed to X, indicating a log record has been stored                                                           |
| li=X | prevLogIndex has changed to X, indicating a log record has been stored                                                          |
| ci=X | Indicates commitIndex has changed to X, meaning log record has been committed, and possibly applied depending on type of record |
| n=X  | Indicates a change in networks status, X=1 means re-joined majority network, X=2 means partitioned to minority network          |

** Notes about interpreting traces
The way in which the traces are collected can occasionally obscure what is going on. A case in point is the commit of records at followers.
The commit process is triggered by an append_entries message arriving at the follower with a commitIndex value that exceeds the local
commit index, and that matches a record in the local log. This starts the commit process AFTER the response message is sent. You might
be expecting it to be prior to sending the response, in bound, as is often said. Whether this is expected behavior is not called out
as an element of the Raft protocol. It is certainly not required, however, as the follower doesn't report the commit index back to the
leader.

The definition of the commit state for a record is that a majority of nodes (leader and followers) have saved the record. Once
the leader detects this it applies and commits the record. At some point it will send another append_entries to the followers and they
will apply and commit. Or, if the leader dies before doing this, the next leader will commit by implication when it sends a term start
log record.

So when you are looking at the traces, you should not expect to see the commit index increas at a follower until some other message
traffic occurs, because the tracing function only checks the commit index at message transmission boundaries.






