* Test test_partition_2_leader from file tests/test_partition_1.py


    Tests that the correct state results when a network partitions and leaves the leader
    isolated from the majority of the cluster nodes, and then rejoins the majority network.

    This is verified by completing an election, and running a state machine command to
    establish replicated state.

    Then the leader is partitioned, then a new election is held. After completing the election,
    a new state machine command is executed, which should succeed because the
    new leader has a quorum.

    After that log record is replicated, the old leader is allowed to rejoin the majority network.

    The old leader is prodded to send out a heartbeat. This will get rejections and the old
    leader should notice the new term in the responses. When it does, it will resign.

    Finally a heartbeat sequence is executed so that the old leader sees then new
    log state from the new leader, and it will tell the leader to catch it up with
    an additional append_entries message.

    When all that is done, the state machine state at the old leader should match the replicated
    state in the other nodes.
    
    Timers are disabled, so all timer driven operations such as heartbeats are manually triggered.
    


 *[[condensed Trace Table Legend][Table legend]] located after last table in file*

** Initial election, normal
-----------------------------------------------------------------------------------------------------------------------------------------------------------
|  N-1   | N-1                          | N-1       | N-2   | N-2                          | N-2       | N-3   | N-3                          | N-3       |
|  Role  | Op                           | Delta     | Role  | Op                           | Delta     | Role  | Op                           | Delta     |
|  FLWR  | STARTED                      |           | FLWR  | STARTED                      |           | FLWR  | STARTED                      |           |
|  CNDI  | NEW ROLE                     |           | FLWR  |                              |           | FLWR  |                              |           |
|  CNDI  | p_v_r->N-2 t=1 li=0 lt=0     |           | FLWR  |                              |           | FLWR  |                              |           |
|  CNDI  | p_v_r->N-3 t=1 li=0 lt=0     |           | FLWR  |                              |           | FLWR  |                              |           |
|  CNDI  |                              |           | FLWR  | N-1->p_v_r t=1 li=0 lt=0     |           | FLWR  |                              |           |
|  CNDI  |                              |           | FLWR  | p_v->N-1 yes=True            |           | FLWR  |                              |           |
|  CNDI  |                              |           | FLWR  |                              |           | FLWR  | N-1->p_v_r t=1 li=0 lt=0     |           |
|  CNDI  |                              |           | FLWR  |                              |           | FLWR  | p_v->N-1 yes=True            |           |
|  CNDI  | N-2->p_v yes=True            | t=1       | FLWR  |                              |           | FLWR  |                              |           |
|  CNDI  | poll->N-2 t=1 li=0 lt=1      |           | FLWR  |                              |           | FLWR  |                              |           |
|  CNDI  | poll->N-3 t=1 li=0 lt=1      |           | FLWR  |                              |           | FLWR  |                              |           |
|  CNDI  | N-3->p_v yes=True            |           | FLWR  |                              |           | FLWR  |                              |           |
|  CNDI  |                              |           | FLWR  | N-1->poll t=1 li=0 lt=1      | t=1       | FLWR  |                              |           |
|  CNDI  |                              |           | FLWR  | vote->N-1 yes=True           |           | FLWR  |                              |           |
|  CNDI  |                              |           | FLWR  |                              |           | FLWR  | N-1->poll t=1 li=0 lt=1      | t=1       |
|  CNDI  |                              |           | FLWR  |                              |           | FLWR  | vote->N-1 yes=True           |           |
|  LEAD  | N-2->vote yes=True           | lt=1 li=1 | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | NEW ROLE                     |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | ae->N-2 t=1 i=0 lt=0 e=1 c=0 |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | ae->N-3 t=1 i=0 lt=0 e=1 c=0 |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | N-3->vote yes=True           |           | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  |                              |           | FLWR  | N-1->ae t=1 i=0 lt=0 e=1 c=0 | lt=1 li=1 | FLWR  |                              |           |
|  LEAD  |                              |           | FLWR  | ae_reply->N-1 ok=True mi=1   |           | FLWR  |                              |           |
|  LEAD  |                              |           | FLWR  |                              |           | FLWR  | N-1->ae t=1 i=0 lt=0 e=1 c=0 | lt=1 li=1 |
|  LEAD  |                              |           | FLWR  |                              |           | FLWR  | ae_reply->N-1 ok=True mi=1   |           |
|  LEAD  | N-2->ae_reply ok=True mi=1   | ci=1      | FLWR  |                              |           | FLWR  |                              |           |
|  LEAD  | N-3->ae_reply ok=True mi=1   |           | FLWR  |                              |           | FLWR  |                              |           |
-----------------------------------------------------------------------------------------------------------------------------------------------------------
** Election complete, running a command 
-----------------------------------------------------------------------------------------------------------------------------------------------
|  N-1   | N-1                          | N-1   | N-2   | N-2                          | N-2   | N-3   | N-3                          | N-3   |
|  Role  | Op                           | Delta | Role  | Op                           | Delta | Role  | Op                           | Delta |
|  LEAD  | CMD START                    |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | ae->N-2 t=1 i=1 lt=1 e=1 c=1 | li=2  | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | ae->N-3 t=1 i=1 lt=1 e=1 c=1 |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  | N-1->ae t=1 i=1 lt=1 e=1 c=1 | li=2  | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  | ae_reply->N-1 ok=True mi=2   |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |                              |       | FLWR  | N-1->ae t=1 i=1 lt=1 e=1 c=1 | li=2  |
|  LEAD  |                              |       | FLWR  |                              |       | FLWR  | ae_reply->N-1 ok=True mi=2   |       |
|  LEAD  | N-2->ae_reply ok=True mi=2   | ci=2  | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  | N-3->ae_reply ok=True mi=2   |       | FLWR  |                              |       | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  | N-1->ae t=1 i=2 lt=1 e=0 c=2 | ci=2  | FLWR  |                              |       |
|  LEAD  |                              |       | FLWR  |                              |       | FLWR  | N-1->ae t=1 i=2 lt=1 e=0 c=2 | ci=2  |
|  LEAD  | CMD DONE                     |       | FLWR  |                              |       | FLWR  |                              |       |
-----------------------------------------------------------------------------------------------------------------------------------------------
** Command complete, partitioning leader 
--------------------------------------------------------------------------
|  N-1   | N-1       | N-1   | N-2   | N-2 | N-2   | N-3   | N-3 | N-3   |
|  Role  | Op        | Delta | Role  | Op  | Delta | Role  | Op  | Delta |
|  LEAD  | NETSPLIT  |       | FLWR  |     |       | FLWR  |     |       |
--------------------------------------------------------------------------
** Holding new election, node 2 will win 
------------------------------------------------------------------------------------------------------------------------------
|  N-1   | N-1 | N-1   | N-2   | N-2                          | N-2       | N-3   | N-3                          | N-3       |
|  Role  | Op  | Delta | Role  | Op                           | Delta     | Role  | Op                           | Delta     |
|  LEAD  |     |       | CNDI  | NEW ROLE                     |           | FLWR  |                              |           |
|  LEAD  |     | n=2   | CNDI  | p_v_r->N-3 t=2 li=2 lt=1     |           | FLWR  |                              |           |
|  LEAD  |     | n=2   | CNDI  |                              |           | FLWR  | N-2->p_v_r t=2 li=2 lt=1     |           |
|  LEAD  |     | n=2   | CNDI  |                              |           | FLWR  | p_v->N-2 yes=True            |           |
|  LEAD  |     | n=2   | CNDI  | N-3->p_v yes=True            | t=2       | FLWR  |                              |           |
|  LEAD  |     | n=2   | CNDI  | poll->N-3 t=2 li=2 lt=2      |           | FLWR  |                              |           |
|  LEAD  |     | n=2   | CNDI  |                              |           | FLWR  | N-2->poll t=2 li=2 lt=2      | t=2       |
|  LEAD  |     | n=2   | CNDI  |                              |           | FLWR  | vote->N-2 yes=True           |           |
|  LEAD  |     | n=2   | LEAD  | N-3->vote yes=True           | lt=2 li=3 | FLWR  |                              |           |
|  LEAD  |     | n=2   | LEAD  | NEW ROLE                     |           | FLWR  |                              |           |
|  LEAD  |     | n=2   | LEAD  | ae->N-3 t=2 i=2 lt=1 e=1 c=2 |           | FLWR  |                              |           |
|  LEAD  |     | n=2   | LEAD  |                              |           | FLWR  | N-2->ae t=2 i=2 lt=1 e=1 c=2 | lt=2 li=3 |
|  LEAD  |     | n=2   | LEAD  |                              |           | FLWR  | ae_reply->N-2 ok=True mi=3   |           |
|  LEAD  |     | n=2   | LEAD  | N-3->ae_reply ok=True mi=3   | ci=3      | FLWR  |                              |           |
------------------------------------------------------------------------------------------------------------------------------
** Both node 1 and node 2 think they are leaders, but only node 2 has a quorum, running command there 
----------------------------------------------------------------------------------------------------------------------
|  N-1   | N-1 | N-1   | N-2   | N-2                          | N-2   | N-3   | N-3                          | N-3   |
|  Role  | Op  | Delta | Role  | Op                           | Delta | Role  | Op                           | Delta |
|  LEAD  |     |       | LEAD  | CMD START                    |       | FLWR  |                              |       |
|  LEAD  |     | n=2   | LEAD  | ae->N-3 t=2 i=3 lt=2 e=1 c=3 | li=4  | FLWR  |                              |       |
|  LEAD  |     | n=2   | LEAD  |                              |       | FLWR  | N-2->ae t=2 i=3 lt=2 e=1 c=3 | li=4  |
|  LEAD  |     | n=2   | LEAD  |                              |       | FLWR  | ae_reply->N-2 ok=True mi=4   |       |
|  LEAD  |     | n=2   | LEAD  | N-3->ae_reply ok=True mi=4   | ci=4  | FLWR  |                              |       |
|  LEAD  |     | n=2   | LEAD  |                              |       | FLWR  | N-2->ae t=2 i=4 lt=2 e=0 c=4 | ci=4  |
|  LEAD  |     | n=2   | LEAD  | CMD DONE                     |       | FLWR  |                              |       |
|  LEAD  |     | n=2   | LEAD  |                              |       | FLWR  | ae_reply->N-2 ok=True mi=4   |       |
|  LEAD  |     | n=2   | LEAD  | N-3->ae_reply ok=True mi=4   |       | FLWR  |                              |       |
----------------------------------------------------------------------------------------------------------------------
** Letting old leader re-join majority network
-------------------------------------------------------------------------
|  N-1   | N-1      | N-1   | N-2   | N-2 | N-2   | N-3   | N-3 | N-3   |
|  Role  | Op       | Delta | Role  | Op  | Delta | Role  | Op  | Delta |
|  LEAD  | NETJOIN  | n=1   | LEAD  |     |       | FLWR  |     |       |
-------------------------------------------------------------------------
** Sending heartbeats from old leader, should resign
-----------------------------------------------------------------------------------------------------------------------------------------------
|  N-1   | N-1                          | N-1   | N-2   | N-2                          | N-2   | N-3   | N-3                          | N-3   |
|  Role  | Op                           | Delta | Role  | Op                           | Delta | Role  | Op                           | Delta |
|  LEAD  | ae->N-2 t=1 i=2 lt=1 e=0 c=2 |       | LEAD  |                              |       | FLWR  |                              |       |
|  LEAD  |                              |       | LEAD  | N-1->ae t=1 i=2 lt=1 e=0 c=2 |       | FLWR  |                              |       |
|  LEAD  |                              |       | LEAD  | ae_reply->N-1 ok=False mi=4  |       | FLWR  |                              |       |
|  FLWR  | N-2->ae_reply ok=False mi=4  | t=2   | LEAD  |                              |       | FLWR  |                              |       |
|  FLWR  | NEW ROLE                     |       | LEAD  |                              |       | FLWR  |                              |       |
|  FLWR  | ae->N-3 t=1 i=2 lt=1 e=0 c=2 |       | LEAD  |                              |       | FLWR  |                              |       |
|  FLWR  |                              |       | LEAD  |                              |       | FLWR  | N-1->ae t=1 i=2 lt=1 e=0 c=2 |       |
|  FLWR  |                              |       | LEAD  |                              |       | FLWR  | ae_reply->N-1 ok=False mi=4  |       |
|  FLWR  | N-3->ae_reply ok=False mi=4  |       | LEAD  |                              |       | FLWR  |                              |       |
-----------------------------------------------------------------------------------------------------------------------------------------------
** Sending heartbeats from new leader, sould catch up old leader
--------------------------------------------------------------------------------------------------------------------------------------------------------
|  N-1   | N-1                          | N-1            | N-2   | N-2                          | N-2   | N-3   | N-3                          | N-3   |
|  Role  | Op                           | Delta          | Role  | Op                           | Delta | Role  | Op                           | Delta |
|  FLWR  |                              |                | LEAD  | ae->N-1 t=2 i=4 lt=2 e=0 c=4 |       | FLWR  |                              |       |
|  FLWR  | N-2->ae t=2 i=4 lt=2 e=0 c=4 |                | LEAD  |                              |       | FLWR  |                              |       |
|  FLWR  | ae_reply->N-2 ok=False mi=2  |                | LEAD  |                              |       | FLWR  |                              |       |
|  FLWR  |                              |                | LEAD  | N-1->ae_reply ok=False mi=2  |       | FLWR  |                              |       |
|  FLWR  |                              |                | LEAD  | ae->N-3 t=2 i=4 lt=2 e=0 c=4 |       | FLWR  |                              |       |
|  FLWR  |                              |                | LEAD  |                              |       | FLWR  | N-2->ae t=2 i=4 lt=2 e=0 c=4 |       |
|  FLWR  |                              |                | LEAD  |                              |       | FLWR  | ae_reply->N-2 ok=True mi=4   |       |
|  FLWR  |                              |                | LEAD  | N-3->ae_reply ok=True mi=4   |       | FLWR  |                              |       |
|  FLWR  |                              |                | LEAD  | ae->N-1 t=2 i=2 lt=1 e=1 c=4 |       | FLWR  |                              |       |
|  FLWR  | N-2->ae t=2 i=2 lt=1 e=1 c=4 | lt=2 li=3 ci=3 | LEAD  |                              |       | FLWR  |                              |       |
|  FLWR  | ae_reply->N-2 ok=True mi=3   |                | LEAD  |                              |       | FLWR  |                              |       |
|  FLWR  |                              |                | LEAD  | N-1->ae_reply ok=True mi=3   |       | FLWR  |                              |       |
|  FLWR  |                              |                | LEAD  | ae->N-1 t=2 i=3 lt=2 e=1 c=4 |       | FLWR  |                              |       |
|  FLWR  | N-2->ae t=2 i=3 lt=2 e=1 c=4 | li=4 ci=4      | LEAD  |                              |       | FLWR  |                              |       |
|  FLWR  | ae_reply->N-2 ok=True mi=4   |                | LEAD  |                              |       | FLWR  |                              |       |
|  FLWR  |                              |                | LEAD  | N-1->ae_reply ok=True mi=4   |       | FLWR  |                              |       |
--------------------------------------------------------------------------------------------------------------------------------------------------------


* Condensed Trace Table Legend
All the items in these legends labeled N-X are placeholders for actual node id values,
actual values will be N-1, N-2, N-3, etc. up to the number of nodes in the cluster. Yes, One based, not zero.

| Column Label | Description     | Details                                                                                        |
| N-X Role     | Raft Role       | FLWR = Follower CNDI = Candidate LEAD = Leader                                                 |
| N-X Op       | Activity        | Describes a traceable event at this node, see separate table below                             |
| N-X Delta    | State change    | Describes any change in state since previous trace, see separate table below                   |


** "Op" Column detail legend
| Value         | Meaning                                                                                      |
| STARTED       | Simulated node starting with empty log, term=0                                               |
| CMD START     | Simulated client requested that a node (usually leader, but not for all tests) run a command |
| CMD DONE      | The previous requested command is finished, whether complete, rejected, failed, whatever     |
| CRASH         | Simulating node has simulated a crash                                                        |
| RESTART       | Previously crashed node has restarted. Look at delta column to see effects on log, if any    |
| NEW ROLE      | The node has changed Raft role since last trace line                                         |
| NETSPLIT      | The node has been partitioned away from the majority network                                 |
| NETJOIN       | The node has rejoined the majority network                                                   |
| ae->N-X       | Node has sent append_entries message to N-X, next line in this table explains                |
| (continued)   | t=1 means current term is 1, i=1 means prevLogIndex=1, lt=1 means prevLogTerm=1              |
| (continued)   | c=1 means sender's commitIndex is 1,                                                         |
| (continued)   | e=2 means that the entries list in the message is 2 items long. eXo=0 is a heartbeat         |
| N-X->ae_reply | Node has received the response to an append_entries message, details in continued lines      |
| (continued)   | ok=(True or False) means that entries were saved or not, mi=3 says log max index = 3         |
| poll->N-X     | Node has sent request_vote to N-X, t=1 means current term is 1 (continued next line)         |
| (continued)   | li=0 means prevLogIndex = 0, lt=0 means prevLogTerm = 0                                      |
| N-X->vote     | Node has received request_vote response from N-X, yes=(True or False) indicates vote value   |
| p_v_r->N-X    | Node has sent pre_vote_request to N-X, t=1 means proposed term is 1 (continued next line)    |
| (continued)   | li=0 means prevLogIndex = 0, lt=0 means prevLogTerm = 0                                      |
| N-X->p_v      | Node has received pre_vote_response from N-X, yes=(True or False) indicates vote value       |
| m_c->N-X      | Node has sent memebership change to N-X op is add or remove and n is the node affected       |
| N-X->m_cr     | Node has received membership change response from N-X, ok indicates success value            |
| p_t->N-X      | Node has sent power transfer command N-X so node should assume power                         |
| N-X->p_tr     | Node has received power transfer response from N-X, ok indicates success value               |
| sn->N-X       | Node has sent snopshot copy command N-X so X node should apply it to local snapshot          |
| N-X>snr       | Node has received snapshot response from N-X, s indicates success value                      |

** "Delta" Column detail legend
Any item in this column indicates that the value of that item has changed since the last trace line

| Item | Meaning                                                                                                                         |
| t=X  | Term has changed to X                                                                                                           |
| lt=X | prevLogTerm has changed to X, indicating a log record has been stored                                                           |
| li=X | prevLogIndex has changed to X, indicating a log record has been stored                                                          |
| ci=X | Indicates commitIndex has changed to X, meaning log record has been committed, and possibly applied depending on type of record |
| n=X  | Indicates a change in networks status, X=1 means re-joined majority network, X=2 means partitioned to minority network          |

** Notes about interpreting traces
The way in which the traces are collected can occasionally obscure what is going on. A case in point is the commit of records at followers.
The commit process is triggered by an append_entries message arriving at the follower with a commitIndex value that exceeds the local
commit index, and that matches a record in the local log. This starts the commit process AFTER the response message is sent. You might
be expecting it to be prior to sending the response, in bound, as is often said. Whether this is expected behavior is not called out
as an element of the Raft protocol. It is certainly not required, however, as the follower doesn't report the commit index back to the
leader.

The definition of the commit state for a record is that a majority of nodes (leader and followers) have saved the record. Once
the leader detects this it applies and commits the record. At some point it will send another append_entries to the followers and they
will apply and commit. Or, if the leader dies before doing this, the next leader will commit by implication when it sends a term start
log record.

So when you are looking at the traces, you should not expect to see the commit index increas at a follower until some other message
traffic occurs, because the tracing function only checks the commit index at message transmission boundaries.






