@startuml
!pragma ratio .5
skinparam componentStyle rectangle
skinparam padding 10
skinparam monochrome false
skinparam component {
  BackgroundColor<<Raft>> #99CCFF
  BackgroundColor<<User>> #CCFFCC
  FontSize 14
}
hide empty members
cloud "Raft Cluster" {
  node [Follower Node2] as node2
  node [Follower Node3] as node3
  note right: ... to N nodes\n in the cluster
}
node {
    package "User authored" {
    	[Application Server Core] as app_core #Lightyellow
	[State Machine] as app_sm #Lightyellow
    	[Application DB] as app_db #Lightblue
    	[SnapShotToolAPI] as snaptool #Lightblue
    	[PilotAPI] as pilot #Lightblue
    }
    package "Raft Engine" {
        [DeckAPI] as hull #Coral
    	[LogAPI] as log #Coral
	[Leader Role] as role #Lightgreen
    }
}
app_core --> hull
hull --> pilot
hull --> snaptool
role --> node2
role --> node3
skinparam legend {
  backgroundColor #GhostWhite
  entrySeparator #GhostWhite
}

legend 
  <#GhostWhite,#GhostWhite>|        |= __Legend__ |
  |<#Lightyellow>   | Defined and implemented by user|
  |<#Lightblue>  | Defined by Raft Engine, implemented by user|
  |<#Coral>  | Defined and implemment by Raft Engine|
  |<#Lightgreen> | Internal Raft Engine component|
endlegend
@enduml
